version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: demo-spring-amqp-fanout-rabbitmq
    ports:
      - 20000:15672

  demo-01:
    image: adonis/demo-spring-amqp-fanout:1.0
    container_name: demo-spring-amqp-fanout-01
    ports:
      - 9001:9999
    depends_on:
      - rabbit

  demo-02:
    image: adonis/demo-spring-amqp-fanout:1.0
    container_name: demo-spring-amqp-fanout-02
    ports:
      - 9002:9999
    depends_on:
      - rabbit

  demo-03:
    image: adonis/demo-spring-amqp-fanout:1.0
    container_name: demo-spring-amqp-fanout-03
    ports:
      - 9003:9999
    depends_on:
      - rabbit

networks:
  default:
    external: 
      name: demo-spring-amqp-fanout-subnet